# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Azuredevops
  demands:
   -  mvn

steps:
  
  - script: |
      sudo apt-get update
      sudo apt-get install -y openjdk-17-jdk
      echo "Installed Java:"
      java -version
    displayName: 'Install Java 17'



  - task: Maven@4
    inputs:
      mavenPOMFile: 'order-service/pom.xml'
      
      javaHomeOption: 'Path'
      jdkDirectory: '/usr/lib/jvm/java-17-openjdk-amd64'
      publishJUnitResults: true

      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      
      mavenVersionOption: 'Default'


  - task: CopyFiles@2
    inputs:
      Contents: '**/target/*.jar'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'


  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Pipeline.Workspace)'   
      publishLocation: 'pipeline'
      artifact: 'drop'
        

